#include <funcs.h>

UART_HandleTypeDef huart4; // huart4 is a basic timer structure that stores UART configuration and other parameters. Code generated by STM32CubeIDE

/* 
    Main function with 'while loop' 
*/
int main(void)
{
  /* Main inint fucntions. Code generated by STM32CubeIDE */ 
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();
  MX_UART4_Init();
  /*******************************************************/

  __HAL_UART_ENABLE_IT(&huart4, UART_IT_RXNE);  // Enable UART RX not empty interrupt 

  /* 
    While loop 
  */
  while (1)
  {
	  uart_routine();   // Call UART rotine function that process new bytes
	  send_next_byte(); // Call sending function
  }
}

/*  
  UART configuration

  Code generated by STM32CubeIDE 
*/
static void MX_UART4_Init(void)
{
  huart4.Instance = UART4;
  huart4.Init.BaudRate = 460800;
  huart4.Init.WordLength = UART_WORDLENGTH_8B;
  huart4.Init.StopBits = UART_STOPBITS_1;
  huart4.Init.Parity = UART_PARITY_NONE;
  huart4.Init.Mode = UART_MODE_TX_RX;
  huart4.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart4.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&huart4) != HAL_OK)
  {
    Error_Handler();
  }
}