#include <funcs.h>

uint8_t rx_byte;							// UART RX byte valiable
extern UART_HandleTypeDef huart4; 			// huart4 is a basic timer structure that stores UART configuration and other parameters. Code generated by STM32CubeIDE
extern uint8_t rx_buffer[UART_BUFF_SIZE];	// RX circular buffer 
extern uint16_t processed;					// Processed byte position
extern uint16_t received;					// Received byte position

/*
    This function handles UART global interrupt. Generated by STM32CubeIDE
*/
void UART4_IRQHandler(void)
{
	if (huart4.Instance->SR & UART_FLAG_RXNE){  // Check if the flag RX not empty (RXNE)
		uint16_t i = received + 1;				// Try to increse received byte position

		if (i == UART_BUFF_SIZE){				// Check if increased position is equal size of UART buffer size
			i = 0;								// Set increased position = 0
		}

		if (i != processed){					// Check if increased received position is not equal processed position
			rx_byte = huart4.Instance->DR;		// Read new byte from Data Register of UART
			rx_buffer[received] = rx_byte;		// Add received byte into buffer
			received = i;						// Set new received position
		}
	}
	return; //It is necessary that everything is executed as quickly as possible, therefore return before the HAL function
  HAL_UART_IRQHandler(&huart4);
}