TIM_HandleTypeDef htim6;            // htim6 is a basic timer structure that stores configuration and other parameters. Code generated by STM32CubeIDE

#define ADC_CLOCK_CNT			    300   // Variable that acts as a prescaler for the timer for ADC_routine
                                    // In this case, the frequency will be 100 Hz, since the timer frequency is configured at 30 khz.  
                                    // 30000 hz / 300 = 100 hz

#define PORT_ONE_CLOCK_CNT		100   // Variable that acts as a prescaler for the timer for first port toggling
                                    // In this case, the frequency will be 300 Hz, since the timer frequency is configured at 30 khz.  
                                    // 30000 hz / 100 = 300 hz

#define PORT_TWO_CLOCK_CNT		30    // Variable that acts as a prescaler for the timer for second port toggling
                                    // In this case, the frequency will be 1 kHz, since the timer frequency is configured at 30 khz.  
                                    // 30000 hz / 30 = 1000 hz

#define PORT_THREE_CLOCK_CNT	3     // Variable that acts as a prescaler for the timer for third port toggling
                                    // In this case, the frequency will be 10 kHz, since the timer frequency is configured at 30 khz.  
                                    // 30000 hz / 3 = 10000 hz

uint32_t adc_measurement;           // Temp variable for ADC measurement
uint32_t adc_result;                // Variable for result of the calculating the average value of ADC meashures
myAdc_t myAdc;                      // Variable for ADC structure
myPort_t myPort;                    // Variable for PORT structure

extern uint16_t ticks_count;        // External variable that stores the number of timer 'ticks'

/* 
    Main function with 'while loop' 
*/
int main(void)
{
  /* Main inint fucntions. Code generated by STM32CubeIDE */ 
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();
  MX_TIM6_Init();
  /*******************************************************/

  HAL_TIM_Base_Start_IT(&htim6);// Starts a timer in interrupt generation mode. Starts a timer and enables interrupts.

  /* 
      While loop 
  */
  while (1)
  {
	  if (ticks_count % PORT_ONE_CLOCK_CNT == 0){ // If the remainder of dividing the number of timer ticks by 100 is 0 (for 300 Hz)
		  myPort.pin0 ^= 1; // Toggle pin0 
	  }

	  if (ticks_count % PORT_TWO_CLOCK_CNT == 0){ // If the remainder of dividing the number of timer ticks by 30 is 0 (for 1 kHz)
		  myPort.pin1 ^= 1; // Toggle pin1 
	  }

	  if (ticks_count % PORT_THREE_CLOCK_CNT == 0){ // If the remainder of dividing the number of timer ticks by 3 is 0 (for 10 kHz)
		  myPort.pin2 ^= 1; // Toggle pin2
	  }

	  if (ticks_count % ADC_CLOCK_CNT == 0){  // If the remainder of dividing the number of timer ticks by 100 is 0 (for 100 Hz)
		  adc_measurement = get_adc_measure();      // Call the abstract function that return the ADC measurement
		  add_adc_measure(&myAdc, adc_measurement); // Add the ADC measurement to myAdc varible

		  if (myAdc.measuremnts_count == ADC_MEASURES_CNT){     // Check if count of ticks (measures) equal 32
			  adc_result = calculate_adc_measurements(&myAdc);    // The result is stored in a variable adc_result
		  }

      ticks_count = 0; // Reset ticsk count
	  }
  }
}

/*  
    Timer configuration
    The frequency of the timer clocks is 16MHz
    The prescaler of the timer is 15999 (16000)
    The period of the time is 29 (30)
    16 000 000 / 16 000 = 1 000
    1 000 * 30 = 30 000
    Thus the frequency of the timer is 30 kHz

    Code generated by STM32CubeIDE 
*/
static void MX_TIM6_Init(void)
{
  TIM_MasterConfigTypeDef sMasterConfig = {0};

  htim6.Instance = TIM6;
  htim6.Init.Prescaler = 15999;
  htim6.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim6.Init.Period = 29;
  htim6.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
  if (HAL_TIM_Base_Init(&htim6) != HAL_OK)
  {
    Error_Handler();
  }
  sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
  sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
  if (HAL_TIMEx_MasterConfigSynchronization(&htim6, &sMasterConfig) != HAL_OK)
  {
    Error_Handler();
  }

}